"""created category model & update book

Revision ID: 559c9fd0bea4
Revises: a3b45058deb2
Create Date: 2025-12-26 10:52:40.972879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559c9fd0bea4'
down_revision: Union[str, Sequence[str], None] = '2572de099bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'category_id')
    # ### end Alembic commands ###
